create database Company;
use Company;
drop table Account;
create table Account(
	TT  int AUTO_INCREMENT primary key,
	NAME VARCHAR(50),
    IDNAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    ADDRESS VARCHAR(50),
    CITY VARCHAR(50),
    COUNTRY VARCHAR(50),
    ROLE VARCHAR(50)
);
insert INTO  Account(NAME, IDNAME, PASSWORD,ADDRESS,CITY,COUNTRY,ROLE) VALUES ("Thành Nhật", "TMA1", "123456","17 Nguyễn Văn Trỗi","Quy Nhơn","Việt Nam","ADMIN");
insert INTO  Account(NAME, IDNAME, PASSWORD,ADDRESS,CITY,COUNTRY,ROLE) VALUES ("Đức Ngọc", "TMA2", "123456","36 Hùng Vương","Quy Nhơn","Việt Nam","ADMIN");
insert INTO  Account(NAME, IDNAME, PASSWORD,ADDRESS,CITY,COUNTRY,ROLE) VALUES ("Ronaldo", "TMA4", "123456","Wall Street 46","Chicago","USA","MEMBER");
insert INTO  Account(NAME, IDNAME, PASSWORD,ADDRESS,CITY,COUNTRY,ROLE) VALUES ("MESSI", "TMA3", "123456","Wall Street 46","Chicago","USA","MENBER");
insert INTO  Account(NAME, IDNAME, PASSWORD,ADDRESS,CITY,COUNTRY,ROLE) VALUES ("BECKHAM", "TMA6", "123456","Wall Street 46","Chicago","USA","MENBER");
insert INTO  Account(NAME, IDNAME, PASSWORD,ADDRESS,CITY,COUNTRY,ROLE) VALUES ("XAVI", "TMA7", "123456","Wall Street 46","Chicago","USA","MENBER");
insert INTO  Account(NAME, IDNAME, PASSWORD,ADDRESS,CITY,COUNTRY,ROLE) VALUES ("HUNG MAI", "TMA8", "123456","Wall Street 46","Chicago","USA","MENBER");
insert INTO  Account(NAME, IDNAME, PASSWORD,ADDRESS,CITY,COUNTRY,ROLE) VALUES ("LE VAN THO", "TMA9", "123456","Wall Street 46","Chicago","USA","MENBER");
insert INTO  Account(NAME, IDNAME, PASSWORD,ADDRESS,CITY,COUNTRY,ROLE) VALUES ("DUC THANH", "TMA10", "123456","Wall Street 46","Chicago","USA","MENBER");
insert INTO  Account(NAME, IDNAME, PASSWORD,ADDRESS,CITY,COUNTRY,ROLE) VALUES ("BECK", "TMA11", "123456","Wall Street 46","Chicago","USA","MENBER");
insert INTO  Account(NAME, IDNAME, PASSWORD,ADDRESS,CITY,COUNTRY,ROLE) VALUES ("LONG", "TMA12", "123456","Wall Street 46","Chicago","USA","MENBER");

select * from Account limit 2;
SELECT * FROM Account where NAME LIKE '%s%' or IDNAME LIKE '%s%' or CITY LIKE '%s%' or COUNTRY LIKE '%s%' or ROLE LIKE '%s'

UPDATE Account SET NAME="Thành Nhật", PASSWORD = "123456", ADDRESS="17 Nguyễn Văn Trỗi", CITY ="QUY NHON", COUNTRY="VIETNAM" WHERE IDNAME="TMA1"
